### ISSUE TITLE
view.dart里面的toast()会报错

### ISSUE THREAD

**Issue by xflcx1991** [yohom/decorated_flutter#5]
我是在 amap_location_fluttify 这个项目的example看到在拒绝权限后有调用`toast('需要定位权限!');`但实际运行拒绝后会报错，给予权限能获取定位。应该是这里`toast`的问题
环境：小米6，dart：2.7 ，flutter：v1.12.13+hotfix.8
pubspec.yaml文件里
> environment:
>   sdk: ">=2.3.0 <3.0.0"

以下是报错的头几行内容，实际运行上述example就能看到。
> E/flutter (19436): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: No element
E/flutter (19436): #0      Iterable.first (dart:core/iterable.dart:520:7)
E/flutter (19436): #1      showToast (package:oktoast/src/core/toast.dart:45:34)
E/flutter (19436): #2      toast (package:decorated_flutter/src/utils/view.dart:25:3)
E/flutter (19436): #3      requestPermission (package:clima/screens/loading_screen.dart:46:5)

**Comment by yohom** [comment]
这个应该是最上层没有套Toast widget，你套一下应该就可以了。参考下toast这个插件的说明。

**Comment by xflcx1991** [comment]
> 
> 
> 这个应该是最上层没有套Toast widget，你套一下应该就可以了。参考下toast这个插件的说明。

感谢回复，是可以了。不过我还是直接引用 oktoast 的 showToast 好了。

**Comment by xflcx1991** [comment]
> 
> 
> 这个应该是最上层没有套Toast widget，你套一下应该就可以了。参考下toast这个插件的说明。

但是请问为什么 example 没有套 OKToast 也能正常运行? 是本项目`decorated_flutter`做了内部的操作?

**Comment by yohom** [comment]
应该是某个widget里已经套过了。这个问题不大的，你套一下就ok。我先关闭咯。
